name: Azure Static Web Apps testing preview

on:
  workflow_dispatch:  # Only run when you click "Run workflow"

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_PEBBLE_001BBC61E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"   # adjust if needed
          api_location: ""    # optional
          output_location: "." # adjust if needed

  close_pull_request_job:
    # This job is only needed if you want to auto-close preview environments when PRs close.
    # If you want manual-only, you can remove this whole job.
    if: false
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_PEBBLE_001BBC61E }}
          action: "close"
